[package]
name = "ml-inference"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ndarray = "0.15"
ort = { version = "2.0.0-rc.10", features = ["half", "download-binaries"] }
thiserror = "2.0.17"